igblast/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home , name='home'),
    path('datasets/<species>/<locus>/<chain>/<geneset>/', views.send_file, name='send_file'),
    path('datasets/', views.datasets, name='datasets'),
    path('search/', views.search, name='search'),
    path('result/', views.result, name='result'),
    path('about/', views.about, name='about'),

]

igquery/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('igblast.urls')),
]

igblast/models.py
from django.db import models
from django.core.validators import MinLengthValidator, MaxLengthValidator
from simple_history.models import HistoricalRecords

class Species(models.Model):
    name = models.CharField(max_length=200, unique=True)
    aux = models.CharField(max_length=200, blank=True)
    history = HistoricalRecords()

    def __str__(self):
        return self.name

class Locus(models.Model):
    name = models.CharField(max_length=200)
    species = models.ForeignKey(Species, on_delete=models.CASCADE)
    history = HistoricalRecords()

    def __str__(self):
        return self.name

class Chain(models.Model):
    name = models.CharField(max_length=200)
    species = models.ForeignKey(Species, on_delete=models.CASCADE)
    locus = models.ForeignKey(Locus, on_delete=models.CASCADE)
    history = HistoricalRecords()

    def __str__(self):
        return self.name

class Geneset(models.Model):
    type = models.CharField(choices=[
        ('V','V gene'),
        ('D','D gene'),
        ('J','J gene'),
        ],
        max_length=1,
        default='V'
    )
    history = HistoricalRecords()

    def __str__(self):
        return self.type

class Gene(models.Model):
    name = models.CharField(max_length=200)
    species = models.ForeignKey(Species, on_delete=models.CASCADE)
    chain = models.ForeignKey(Chain, on_delete=models.CASCADE)
    locus = models.ForeignKey(Locus, on_delete=models.CASCADE)
    geneset = models.ForeignKey(Geneset, on_delete=models.CASCADE)
    history = HistoricalRecords()

    def __str__(self):
        return self.name

class Allele(models.Model):
    name = models.CharField(max_length=200)
    species = models.ForeignKey(Species, on_delete=models.CASCADE)
    chain = models.ForeignKey(Chain, on_delete=models.CASCADE)
    locus = models.ForeignKey(Locus, on_delete=models.CASCADE)
    geneset = models.ForeignKey(Geneset, on_delete=models.CASCADE)
    gene = models.ForeignKey(Gene, on_delete=models.CASCADE)
    history = HistoricalRecords()

    def __str__(self):
        return self.name

class Sequence(models.Model):
    species = models.ForeignKey(Species, on_delete=models.CASCADE)
    chain = models.ForeignKey(Chain, on_delete=models.CASCADE)
    locus = models.ForeignKey(Locus, on_delete=models.CASCADE)
    geneset = models.ForeignKey(Geneset, on_delete=models.CASCADE)
    gene = models.ForeignKey(Gene, on_delete=models.CASCADE)
    allele = models.ForeignKey(Allele, on_delete=models.CASCADE)
    sequence = models.TextField()
    source = models.CharField(choices=(
            ('g', "Genomic"),
            ('e', "Expressed"),
        ),
        max_length=1
    )
    history = HistoricalRecords()

    def __str__(self):
        return self.allele.name
    pub_date = models.DateTimeField('date published')

class LogEntry(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    pub_date = models.DateTimeField('date published')
    history = HistoricalRecords()

    def __str__(self):
        return self.title

class Version(models.Model):
    tag = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    history = HistoricalRecords()

    def __str__(self):
        return self.tag

class FastaField(models.Model):
    fasta_text = models.TextField(validators=[MaxLengthValidator(5000), MinLengthValidator(3)])
    species_name = models.CharField(max_length=200, default='')
    locus_name = models.CharField(max_length=200, default='')
    chain_name = models.CharField(max_length=200, default='')
    upload_date = models.DateTimeField(auto_now_add=True, blank=True)
    def __str__(self):
        return str(self.upload_date)

igblast/forms.py
from django import forms
from .models import FastaField

class ModelFormWithFastaField(forms.ModelForm):
    class Meta:
        model = FastaField
        fields = ('fasta_text','species_name','locus_name','chain_name')

igblast/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.http import HttpResponseRedirect

from .models import Locus
from .models import Chain
from .models import Gene
from .models import Geneset
from .models import Species
from .models import Allele
from .models import Sequence

from .models import LogEntry
from .models import FastaField
from .models import Version

from .tasks import process_fasta
from .forms import ModelFormWithFastaField

from django.http import FileResponse
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage

def create_db(species, locus, chain, geneset):
    """
    Create file with specific database
    """
    sp = Species.objects.all()
    if species != 'All':
        sp = [Species.objects.filter(name=species).first()]
    seq_dict = {}
    version = Version.objects.order_by('-id').first() # Overall database version, no need to be in loop
    gset = Geneset.objects.filter(type=geneset).first()
    for s in sp:
        loc = Locus.objects.filter(species=s, name=locus).first()
        ch = Chain.objects.filter(species=s, locus=loc, name=chain).first()
        allele_all = Allele.objects.filter(species=s, locus=loc, chain=ch, geneset=gset).all()
        for allele in allele_all:
            sequence = Sequence.objects.filter(species=s, locus=loc, chain=ch, geneset=gset, allele=allele).first()
            seq_dict[str(allele)] = str(sequence.sequence)

    path = species.replace(' ','-')+'_'+locus+'_'+chain+'_'+geneset+'_'+str(version).replace('.','-')+'.fasta'
    fasta = default_storage.open(path, 'wt')
    for allele_name,allele_seq in seq_dict.items():
        fasta.write(">{}\n{}\n".format(allele_name,allele_seq))
    if len(seq_dict) == 0:
        fasta.write('>dummy\nNNNNNN\n')
    fasta.close()
    return default_storage.path(path)

def send_file(response, species, locus, chain, geneset):
    path = create_db(species, locus, chain, geneset)
    fasta = open(path, 'rb')
    response = FileResponse(fasta)
    return response

def datasets(request):
    """Database overview"""
    context = {}
    for species in Species.objects.all():
        context.setdefault(str(species),{})
        for locus in Locus.objects.filter(species=species):
            context[str(species)].setdefault(str(locus),{})
            for chain in Chain.objects.filter(locus=locus):
                context[str(species)][str(locus)].setdefault(str(chain),{})
                for geneset in Geneset.objects.all():
                    context[str(species)][str(locus)][str(chain)].setdefault(str(geneset),[])
                    for gene in Gene.objects.filter(locus=locus,chain=chain, geneset=geneset):
                        for allele in Allele.objects.filter(gene=gene):
                            context[str(species)][str(locus)][str(chain)][str(geneset)].append(str(allele))

    return render(request, 'igblast/datasets.html', {'context': context})

def home(request):
    latest_changelog_list = LogEntry.objects.order_by('-pub_date')[:5]
    version = Version.objects.order_by('-id').first()
    context = {'latest_changelog_list': latest_changelog_list, 'version': version}
    return render(request, 'igblast/home.html', context)

def search(request):
    species = Species.objects.all()
    locus = set([l.name for l in Locus.objects.distinct()])
    chain = set([l.name for l in Chain.objects.distinct()])
    version = Version.objects.order_by('-id').first()
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ModelFormWithFastaField(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            path = default_storage.save('query.fa', ContentFile(form.cleaned_data['fasta_text']))
            request.session['fasta_file'] = default_storage.path(path)
            if form.cleaned_data['species_name'] != 'All':
                sp = Species.objects.filter(name=form.cleaned_data['species_name']).first()
                request.session['aux'] = sp.aux
            else:
                request.session['aux'] = 'database/rhesus_monkey_gl.aux' # Default aux
            request.session['species'] = form.cleaned_data['species_name']
            # create db
            database = {}
            for geneset in ['V','D','J']:
                database[geneset] = create_db(form.cleaned_data['species_name'],form.cleaned_data['locus_name'], form.cleaned_data['chain_name'], geneset)
            request.session['database'] = database
            # save data in database
            form.save()
            # redirect to a new URL:
            return HttpResponseRedirect('/result/')
    # if a GET (or any other method) we'll create a blank form
    else:
        form = ModelFormWithFastaField()

    return render(request, 'igblast/search.html', {'form':form, 'species':species, 'locus':locus, 'chain':chain, 'version':version})

def result(request):
    if request.session.has_key('fasta_file'):
        fasta_file = request.session.get('fasta_file')
        database = request.session.get('database')
        aux = request.session.get('aux')
        species = request.session.get('species')
        output_file = process_fasta.delay(fasta_file, database, aux)
        return render(request, 'igblast/result.html', {'fasta_text':fasta_file[0:10]+'...', 'table': output_file.get(), 'database':database, 'aux':aux, 'species':species})
    return render(request, 'igblast/result.html')

def about(request):
    return render(request, 'igblast/about.html')

igblast/templates/igblast/about.html
{% extends "igblast/base.html" %}
{% block body_block %}
<div class="container-fluid">
  <br>
  <h3>GKH Lab</h3>
  <small class="text-muted"></small>
  <div class="container-fluid">
    If you are using this database, please cite
    <p>
          <br>
    <i>
       <b>Rhesus and Cynomolgus IGH Genotyping Yields Comprehensive Databases of Germline VDJ Alleles for In-Depth Immunological Studies.</b>
       <br>
       N. Vázquez Bernat, M. Corcoran, I. Nowak, M. Kaduk, X. Castro Dopico, S. Narang, P. Maisonasse,
       <br>
       N. Dereuddre-Bosquet, B. Murrell and G.B. Karlsson Hedestam, Immunity 2021
       <br>
       Available at: <a href="https://pubmed.ncbi.nlm.nih.gov/33484642/">https://pubmed.ncbi.nlm.nih.gov/33484642/</a>.
    </i>
    </p>
    The IgDiscover code used to produce the macaque database is archived at <a href='https://gitlab.com/gkhlab/igdiscover-macaca/-/tree/v0.10b'>v0.10b</a>. The latest version of the software is available at <a href="http://IgDiscover.se">IgDiscover.se</a> and updates will be available from the same site.
    <p>	
    <i>
    	<br>
	<b>VDJ expression signatures of IgM repertoires from rhesus and cynomolgus macaques reveal consistent gene level usage between individuals.</b> 
	<br>
	M. Chernyshev, M. Kaduk, M. Corcoran, G.B. Karlsson Hedestam, Frontiers in Immunology, 2022
	<br>
	Available at: <a href="https://www.frontiersin.org/articles/815680">https://www.frontiersin.org/articles/815680</a>
   </i>
   </p>
   <p>
   <br>
   <i>
	   <b>Addressing IGHV gene structural diversity enhances immunoglobulin repertoire analysis: lessons from rhesus macaque.</b>
	   <br>
	   M. Kaduk, M. Corcoran, G. B. Karlsson Hedestam, Frontiers in Immunology, 2022
	   <br>
	   Available at: <a href="https://www.frontiersin.org/articles/10.3389/fimmu.2022.818440">https://www.frontiersin.org/articles/10.3389/fimmu.2022.818440</a>
   </i>
   </p>
  </div>
</div>
{% endblock %}

igblast/templates/igblast/base.html
<!DOCTYPE html>
<html>
<head>
<title>KIMDB</title>
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous"></link>
<link href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap5.min.css" rel="stylesheet"></link>
<link href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css" rel="stylesheet"></link>
<link href="https://cdn.datatables.net/scroller/2.0.3/css/scroller.dataTables.min.css" rel="stylesheet"></link>
<style>
th, td { white-space: nowrap; }
body {
  font-family: 'Calibri', sans-serif !important;
}
img.dendogram {
	height: 460px;
	width: 400px;
	margin-right: 40%;
}
</style>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	  <div class="container-fluid">
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarNavDropdown">
	      <ul class="navbar-nav">
	        <li class="nav-item">
	          <a class="nav-link active" aria-current="page" href="{%url 'home' %}">Home</a>
	        </li>
	        <li class="nav-item dropdown">
	          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
	            Databases
	          </a>
						<ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
							<li><a class="dropdown-item" href="{%url 'search' %}">Search</a></li>
							<li><a class="dropdown-item" href="{%url 'datasets' %}">Sequences</a></li>
						</ul>
	        </li>
					<li class="nav-item">
						<a class="nav-link" href="{%url 'about' %}">About</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="/admin">Admin</a>
					</li>
	      </ul>
	    </div>
	  </div>
	</nav>

	<div  class="container-fluid">
    {% block body_block %}
    <h1>KIMDB</h1>
    {% endblock %}
	</div>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
	<script
			  src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
			  integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs="
			  crossorigin="anonymous"></script>
	<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap5.min.js"></script>
	<script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
	<script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>
	<script src="https://cdn.datatables.net/scroller/2.0.3/js/dataTables.scroller.min.js"></script>
	<script type="text/javascript">
		$(document).ready(function() {
			var table = $('#tsv').DataTable({
				deferRender: true,
				scrollCollapse: true,
				scrollY: 200,
				scrollX: 500,
				scrollCollapse: true,
				scroller:  true,
				stateSave: true,
				dom: 'lfrtBip',
				buttons: ['csv']
			} );
		} );
	</script>
	</body>
</html>

igblast/templates/igblast/datasets.html
{% extends "igblast/base.html" %}
{% block body_block %}
<br>
<div class="accordion" id="accordionGenes">
  {% for species_name, species_value in context.items %}
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      {% if forloop.first %}
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
      {% else %}
       <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
      {% endif %}
        {{ species_name }}
      </button>
    </h2>
    {% if forloop.first %}
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionGenes">
    {% else %}
     <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionGenes">
    {% endif %}
      <div class="accordion-body">
        <ul class="list-group">
          {% for locus_name, locus_value in species_value.items %}
            <li class="list-group-item">
              <p> {{ locus_name }} locus</p>
              <ul class="list-group">
                {% for chain_name, chain_value in locus_value.items %}
                <li class="list-group-item">
                  <p> {{ chain_name }} chain</p>
                <ul class="list-group">
                  {% for geneset_name, geneset_value in chain_value.items %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                    <a href="{{species_name}}/{{locus_name}}/{{chain_name}}/{{geneset_name}}/">{{ geneset_name }} gene</a>
                    <span class="badge bg-primary rounded-pill">{{ geneset_value |length}}</span>
                    </li>
                  {% endfor %}
                </ul>
                </li>
                {% endfor %}
              </ul>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
  {% endfor %}
  </div>
</div>
{% endblock %}

igblast/templates/igblast/home.html
{% extends "igblast/base.html" %}
{% load markdownify %}
{% block body_block %}
  <br>
  <h3>
  The Karolinska Macaque database
  <small class="text-muted">KIMDB ({{ version }})</small>
  </h3>
  <div class="container-fluid">
  <p>This database incorporates IGHV, IGHJ and IGHD sequences from four subgroups of macaques, namely Indian and Chinese origin Rhesus macaques and Indonesian and Mauritian origin Cynomolgus macaques comprising 45 macaques in total.</p>
  <p>All IGHV and IGHJ sequences in the database were identified using the germline inference tool IgDiscover, as described in Vázquez-Bernat et al. Immunity 2021, PMID: 33484642. In brief, two independent IgM libraries were sequenced for each of 45 macaques (27 rhesus macaques and 18 cynomolgus macaques), utilizing a 3' UMI introduced during cDNA synthesis followed by 5' multiplex set amplification. The study was performed using an updated version of IgDiscover and used the Cirelli et al. IGHV, IGHJ and IGHD sequences as the starting database during germline inference. The resulting combined database contains 1197 IGHV, 53 IGHD and 16 IGHJ alleles. Several alleles were present in both rhesus and cynomolgus macaques.
  </p>
 </div>
 <br>
 {% load static %}

 <div class="container-fluid">

 <div class="clearfix">
   <img src="{% static 'igblast/RhesusIGHV.jpg' %}" class="dendogram col-md-6 float-md-end mb-3 ms-md-3" alt="...">
   <b>Rhesus macaques</b>
   <p>
  Phylogenetic analysis of IGHV alleles identified by IgDiscover in the 27 rhesus macaques (15 Indian origin and 12 Chinese origin). IGHV families are indicated by arcs in different colors and alleles identical to those reported in Cirelli et al. are shown in red dashed lines. The scale bar represents the expected number of nucleotide substitutions per site. A total of 761 IGHV alleles were identified in the 27 animals and the number of alleles in each IGHV family is indicated in the inserted table.</p>
 </div>

 <div class="clearfix">
 <img src="{% static 'igblast/IGHVCynomolgus.jpg' %}" class="dendogram col-md-6 float-md-end mb-3 ms-md-3" alt="...">
   <b>Cynomolgus macaques</b>
   <p>Phylogenetic analysis of IGHV alleles identified by IgDiscover in 18 cynomolgus macaques (12 Mauritian origin and 6 Indonesian origin). IGHV families are indicated by arcs in different colors and alleles identical to those present in the IMGT cynomolgus database (downloaded in May 2020) are shown in red dashed lines. The scale bar represents the expected number of nucleotide substitutions per site. A total of 615 IGHV alleles were identified in the 18 animals and the number of alleles in each IGHV family is indicated in the inserted table.</p>
 </div>
 </div>

  <div class="container-fluid">
  <p class="h3">Changelog</p>
  <div class="list-group">
    {% if latest_changelog_list %}
        {% for logentry in latest_changelog_list %}
            <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
              <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ logentry.title }} </h5>
                <small>{{ logentry.pub_date }}</small>
              </div>
              <small>
              <p class="text-sm-left">{{ logentry.description|markdownify }}</p>
              </small>
            </a>
        {% endfor %}
    {% else %}
        <p class="mb-1">No changelogs are available.</p>
    {% endif %}
  </div>
  </div>
  <br>
{% endblock %}

igblast/templates/igblast/result.html
{% extends "igblast/base.html" %}
{% block body_block %}
<h3>Results</h3>
<div class="container-fluid">
{% if table %}
{% autoescape off %}
  {{ table }}
{% endautoescape %}
{% endif %}
</div>
<script type="text/javascript">
  $(document).ready(function() {
      $('#tsv').DataTable({
        buttons: ['csv']
      } );
  });
</script>
{% endblock %}

igblast/templates/igblast/search.html
{% extends "igblast/base.html" %}
{% block body_block %}
<br>
<div class="container-fluid">
<div class="card">
  <div class="card-header">
    <h3>IgBLAST</h3>
    <div class="card-body">
      <p>Uses IgBLASTn v1.17 tool for quick assignment against KIMDB ({{ version }}). </p>
      <p>To search NGS datasets we recommend you download the standalone <a href="http://docs.igdiscover.se/">IgDiscover</a> program and use our <a href="/datasets/">database</a> for the analysis.</p>
    <form action="/search/" method="post">
      {% csrf_token %}
      <div class="form-group">
        <label class="form-label" for="fastaLabel">Enter nucleotide sequences in FASTA (max 5000 characters)</label>
        <textarea class="form-control" name="fasta_text" rows="4" required id="id_fasta_text"></textarea>
        <br>
      </div>
      <div class="form-group">
        <div class="input-group mb-3">
          <label class="input-group-text" for="locus_nameLabel">Species</label>
          <select class="form-select" name="species_name" required id="id_species_name">
            <option value="All">All</option>
            {% for species_name in species %}
            <option value="{{ species_name }}">{{ species_name }}</option>
            {% endfor %}
          </select>
        </div>
        <div class="input-group mb-3">
          <label class="input-group-text" for="locus_nameLabel">Locus</label>
          <select class="form-select"  name="locus_name" required id="id_locus_name">
            {% for locus_name in locus %}
            <option value="{{ locus_name }}">{{ locus_name }}</option>
            {% endfor %}
          </select>
        </div>
        <div class="input-group mb-3">
          <label class="input-group-text" for="chain_nameLabel">Chain</label>
          <select class="form-select"  name="chain_name" required id="id_chain_name">
            {% for chain_name in chain %}
            <option value="{{ chain_name }}">{{ chain_name }}</option>
            {% endfor %}
          </select>
        </div>
        <p><b>Note:</b> Your query will be stored on the server due to the nature of IgBLASTn program.</p>
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Search</button>
        </div>
    </form>
    </div>
</div>
</div>
</div>
{% endblock %}